import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import { AuthProvider } from '@/contexts/AuthContext'
import { WatchedContentProvider } from '@/contexts/WatchedContentContext'
import { Toaster } from "@/components/ui/sonner"

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Medu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased`}
      >
        <AuthProvider>
          <WatchedContentProvider>
            <NavBar />
            {children}
            <Toaster />
          </WatchedContentProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
